### ISSUE TITLE
前端站点运行时间计算有误

### ISSUE THREAD

**Issue by BakaRice** [oneStarLR/myblog-mybatis#5]
`// 运行时间统计
      function secondToDate(second)`
这里好像有点问题，统计的时间有误，可以因为跨年了 出现了统计数字的错误

**Comment by BakaRice** [comment]
`  var create_time = Math.round(new Date(Date.UTC(2021, 01, 03, 0, 0, 15)).getTime() / 1000);`
替换成下面的写法就对了...菜了，没毛病为什么
`// var create_time = Math.round(new Date('2021-1-3 00:00:00').getTime() / 1000);`

**Comment by youlingdada** [comment]
数字格式吗。哈哈，其实这个数据也是错的，用毫秒计时会出错的，年月日记录会出错
